Incorrect type for siteConfig parameter in Project API #10263
enonic/xp pull request #10264
Opened 2023-09-08 11:13 UTC by alansemenov

2023-09-08 11:29 UTC, edloidas approved these changes

2023-09-08 11:31 UTC, ComLock approved these changes
I have not testes, but that seems consistent with the docs
https://developer.enonic.com/docs/xp/stable/api/lib-project#create

2023-09-08 11:36 UTC, rymsha requested changes
I don't think it is correct, either

Because portal has
```
export type Site<Config> = Content<{
    description?: string;
    siteConfig: SiteConfig<Config> | SiteConfig<Config>[];
}, 'portal:site'>;

export interface SiteConfig<Config> {
    applicationKey: string;
    config: Config;
}

```

or maybe it is correct, because we do expect an array in handler, but very inconvenient. 
And `siteConfig` have a specific structure, too: it must nave applicationKey and config, not just random fields.

2023-09-08 14:52 UTC, alansemenov commented
@rymsha updated

2023-09-11 13:22 UTC, ComLock approved these changes

2023-09-11 13:38 UTC, merged