Issue 10474 remove default repository
enonic/xp pull request #10488
Opened 2024-03-27 12:36 UTC by anatol-sialitski

2024-05-13 08:39 UTC, rymsha commented on modules/core/core-api/src/main/java/com/enonic/xp/content/ContentConstants.java
> +//    @Deprecated
delete dead code

2024-05-13 08:39 UTC, rymsha commented on modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/ApplicationInfoServiceImpl.java
>      public Contents getContentReferences( final ApplicationKey applicationKey )
`@Deprecated`

2024-05-13 08:39 UTC, rymsha commented on modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentServiceImpl.java
>      @Override
`@Deprecated`

2024-05-13 08:39 UTC, rymsha commented on modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectContentEventListener.java
> +            Context currentContext = ContextAccessor.current();
I think we need to copy context before giving it to executor

2024-05-13 12:48 UTC, rymsha requested changes

2024-05-13 12:48 UTC, rymsha commented on modules/lib/lib-portal/src/main/java/com/enonic/xp/lib/portal/current/GetCurrentSiteConfigHandler.java
> +                final Project project = this.projectService.get().get( ProjectName.from( this.request.getRepositoryId() ) );
I would not do it in this PR. It is a tricky topic - where to get project from.
This change introduces ambiguity - project from request, but branch from context

2024-05-13 12:48 UTC, rymsha commented on modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/exception/ExceptionRendererImpl.java
> +            : ( req.isSiteBase() ? callAsContentAdmin( () -> this.contentService.findNearestSiteByPath( req.getContentPath() ) ) : null );
Looks strange - site is in request, bun not siteBase request?

2024-05-15 21:37 UTC, rymsha approved these changes

2024-05-16 08:25 UTC, vbradnitski approved these changes

2024-05-16 08:48 UTC, merged