Implement Harmonized API handler #10522
enonic/xp pull request #10533
Opened 2024-04-30 11:49 UTC by anatol-sialitski

2024-05-13 13:12 UTC, rymsha requested changes

2024-05-13 13:12 UTC, rymsha commented on modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/handler/AssetHandler.java
> +    private static final Pattern PATTERN = Pattern.compile( "([^/^:]+)(?::([^/]+))?/(.+)" );
this pattern looks incorrect. Does not have a start, and disallows `^` in first path element?

2024-05-13 13:12 UTC, rymsha commented on modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/handler/AttachmentHandler.java
>      private static final Pattern PATTERN = Pattern.compile( "([^/]+)/([^/^:]+)(?::([^/]+))?/([^/]+)" );
see above about Pattern

2024-05-13 13:12 UTC, rymsha commented on modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/handler/AttachmentHandler.java
> +    public AttachmentHandler( final @Reference ContentService contentService )
annotations first

2024-05-13 13:12 UTC, rymsha commented on modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/handler/IdentityHandler.java
> +    public IdentityHandler( final @Reference ContentService contentService,
annotations first

2024-05-14 08:45 UTC, anatol-sialitski commented on modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/handler/ApiDispatcher.java
> +                case "attachment", "image" -> IS_GET_HEAD_OPTIONS_METHOD.test( webRequest ) && IS_SITE_BASE.test( webRequest );
It is processed here https://github.com/enonic/xp/pull/10533/files#diff-b86a226c097cefaf9a5bbade35cd5575b151c02401c11d1a06db90402967feb8R77

2024-05-15 14:58 UTC, rymsha requested changes

2024-05-15 14:58 UTC, rymsha commented on modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/handler/AttachmentHandler.java
> +        if ( !IS_SITE_BASE.test( webRequest ) )
Should be before method check - not just here but in other handlers, too

2024-05-16 14:50 UTC, merged