Linter errors after turning on strict mode
enonic/xp pull request #10719
Opened 2024-10-02 11:25 UTC by alansemenov

2024-10-02 13:18 UTC, ComLock requested changes

2024-10-02 13:18 UTC, ComLock commented on modules/lib/lib-admin/src/main/resources/lib/xp/admin.ts
> +interface Portal {
Why not use the types from the source, which is available in the same code repo?

2024-10-02 13:20 UTC, ComLock commented on modules/lib/lib-io/src/main/resources/lib/xp/io.ts
> +        this.res = bean.getResource(key) ;
whitespace oupsie?

2024-10-02 18:35 UTC, anatol-sialitski approved these changes

2024-10-31 07:57 UTC, ComLock approved these changes

2024-10-31 08:06 UTC, anatol-sialitski commented
Awesome work, Alan!

2024-10-31 10:45 UTC, rymsha approved these changes

2024-10-31 10:47 UTC, merged