POC: Make subproject sync interval configurable #8299
enonic/xp pull request #8334
Opened 2020-09-03 09:56 UTC by vbradnitski

2020-09-03 10:01 UTC, jsi commented on modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectContentEventListener.java
> +    private final static Logger LOG = LoggerFactory.getLogger( ProjectContentEventListener.class );
Codacy found an issue: ['static' modifier out of order with the JLS suggestions.](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6117594)

2020-09-03 10:01 UTC, jsi commented on modules/core/core-project/src/main/java/com/enonic/xp/core/impl/project/ProjectEventListener.java
> +    private final static Logger LOG = LoggerFactory.getLogger( ProjectEventListener.class );
Codacy found an issue: ['static' modifier out of order with the JLS suggestions.](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6117594)

2020-09-03 10:01 UTC, jsi commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- modules/core/core-project/src/main/java/com/enonic/xp/core/impl/project/ProjectEventListener.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentProjectSyncActivator.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectNotFoundException.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentProjectSyncTask.java  1
- modules/core/core-api/src/main/java/com/enonic/xp/project/ParentProjectSynchronizer.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectContentEventListener.java  4
         

Clones added
============
- modules/core/core-project/src/main/java/com/enonic/xp/core/impl/project/ProjectEventListener.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectContentEventListener.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6117594&bid=20019677)

2020-09-03 10:22 UTC, rymsha requested changes

2020-09-03 10:22 UTC, rymsha commented on modules/runtime/src/home/config/com.enonic.xp.content.cfg
> +#content.sync.period = 1000
Please use Duration format instead.

2020-09-07 10:32 UTC, jsi commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/core/core-project/src/main/java/com/enonic/xp/core/impl/project/ProjectEventListener.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectNotFoundException.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentProjectSyncTask.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectContentEventListener.java  4
- modules/core/core-api/src/main/java/com/enonic/xp/project/ParentProjectSynchronizer.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentProjectSyncActivator.java  2
         

Clones added
============
- modules/core/core-project/src/main/java/com/enonic/xp/core/impl/project/ProjectEventListener.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectContentEventListener.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6117594&bid=20019677)

2020-09-07 10:35 UTC, rymsha approved these changes

2020-09-07 10:35 UTC, merged