getVersionsForView API doesn't return unpublished version #8314
enonic/xp pull request #8391
Opened 2020-09-21 15:01 UTC by vbradnitski

2020-09-21 15:06 UTC, jsi commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/core/core-api/src/main/java/com/enonic/xp/content/ContentVersion.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/content/GetContentVersionsForViewResultJson.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentVersionFactory.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6211693&bid=20256222)

2020-09-21 15:39 UTC, jsi commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentVersionFactory.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/content/GetContentVersionsForViewResultJson.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6211693&bid=20256222)

2020-09-21 17:29 UTC, rymsha commented on modules/core/core-api/src/main/java/com/enonic/xp/content/ContentVersion.java
> +    public int compareTo( final ContentVersion that )
Leave alone this broken implementation (Deprecate?). Write a separate Comparator. Also See #7440

2020-09-22 10:24 UTC, jsi commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentVersionFactory.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/content/GetContentVersionsForViewResultJson.java  1
         

Complexity decreasing per file
==============================
+ modules/core/core-api/src/main/java/com/enonic/xp/content/ActiveContentVersionEntry.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6211693&bid=20256222)

2020-09-22 10:46 UTC, jsi commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentVersionFactory.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/content/GetContentVersionsForViewResultJson.java  1
         

Complexity decreasing per file
==============================
+ modules/core/core-api/src/main/java/com/enonic/xp/content/ActiveContentVersionEntry.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6211693&bid=20256222)

2020-09-22 12:12 UTC, rymsha requested changes

2020-09-22 12:12 UTC, rymsha commented on modules/core/core-api/src/main/java/com/enonic/xp/content/ContentVersions.java
> +        contentVersions = builder.contentVersions.build();
Use list with sort

2020-09-22 12:12 UTC, rymsha commented on modules/core/core-api/src/main/java/com/enonic/xp/content/GetActiveContentVersionsResult.java
> -        this.activeContentVersions = ImmutableSortedSet.copyOf( builder.activeContentVersions );
Use list with sort

2020-09-22 13:57 UTC, jsi commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentVersionFactory.java  1
- modules/core/core-api/src/main/java/com/enonic/xp/content/ContentVersionDateComparator.java  7
- modules/core/core-api/src/main/java/com/enonic/xp/content/ContentVersion.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/content/GetContentVersionsForViewResultJson.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6211693&bid=20256222)

2020-09-22 14:06 UTC, jsi commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/core/core-api/src/main/java/com/enonic/xp/content/ContentVersionDateComparator.java  5
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/content/GetContentVersionsForViewResultJson.java  1
- modules/core/core-api/src/main/java/com/enonic/xp/content/ContentVersion.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentVersionFactory.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6211693&bid=20256222)

2020-09-22 18:14 UTC, rymsha requested changes

2020-09-22 18:14 UTC, rymsha commented on modules/core/core-api/src/main/java/com/enonic/xp/content/ContentVersionDateComparator.java
> +public class ContentVersionDateComparator
final
Or maybe even internal of ContentVersions, because it is an implementation detail

2020-09-22 18:14 UTC, rymsha commented on modules/core/core-api/src/main/java/com/enonic/xp/content/ContentVersion.java
> +        private NodeCommitId nodeCommitId;
Let's have a second round of we really want to expose id

2020-09-23 09:35 UTC, jsi commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/content/GetContentVersionsForViewResultJson.java  1
- modules/core/core-api/src/main/java/com/enonic/xp/content/ContentVersion.java  1
- modules/core/core-api/src/main/java/com/enonic/xp/content/ContentVersionDateComparator.java  5
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentVersionFactory.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6211693&bid=20256222)

2020-09-23 09:36 UTC, rymsha commented on modules/core/core-api/src/main/java/com/enonic/xp/content/ContentVersionDateComparator.java
> +        Instant thisTime, thatTime;
Codacy found an issue: [Use one line for each declaration, it enhances code readability.](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6220524)

2020-09-23 10:11 UTC, jsi commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/json/content/GetContentVersionsForViewResultJson.java  1
- modules/core/core-api/src/main/java/com/enonic/xp/content/ContentVersionDateComparator.java  5
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentVersionFactory.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6211693&bid=20256222)

2020-09-23 10:18 UTC, rymsha approved these changes

2020-09-23 14:13 UTC, anatol-sialitski approved these changes

2020-09-23 14:17 UTC, merged