toNativeObject does not return null values
enonic/xp pull request #8411
Opened 2020-10-01 08:27 UTC by anatol-sialitski

2020-10-01 08:32 UTC, jsi commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    var bean = __.newBean('com.enonic.xp.lib.content.QueryContentHandler');
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6266265)

2020-10-01 08:32 UTC, jsi commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 19
           

Complexity increasing per file
==============================
- modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js  2
- modules/script/script-impl/src/main/java/com/enonic/xp/script/impl/util/ScriptMapGenerator.java  1
         

Clones added
============
- modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js  13
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6266265&bid=20402577)

2020-10-01 08:32 UTC, jsi commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    var bean = __.newBean('com.enonic.xp.lib.content.GetAttachmentStreamHandler');
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6266265)

2020-10-01 08:32 UTC, jsi commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    var bean = __.newBean('com.enonic.xp.lib.content.ContentExistsHandler');
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6266265)

2020-10-01 08:33 UTC, jsi commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    var bean = __.newBean('com.enonic.xp.lib.content.ContentTypeHandler');
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6266265)

2020-10-01 08:33 UTC, jsi commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    var bean = __.newBean('com.enonic.xp.lib.content.GetSiteHandler');
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6266265)

2020-10-01 08:33 UTC, jsi commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    bean.highlight = __.toScriptValue(params.highlight);
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6266265)

2020-10-01 08:33 UTC, rymsha commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 19
           

Complexity increasing per file
==============================
- modules/portal/portal-impl/src/test/java/com/enonic/xp/portal/impl/controller/PortalResponseSerializerTest.java  1
- modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js  2
- modules/script/script-impl/src/main/java/com/enonic/xp/script/impl/util/ScriptMapGenerator.java  1
         

Clones added
============
- modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js  13
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6266264&bid=20402576)

2020-10-01 08:33 UTC, rymsha commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    var value = params[name];
Codacy found an issue: [Variable Assigned to Object Injection Sink](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6266264)

2020-10-01 08:33 UTC, jsi commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    return __.toNativeObjectIncludeNullValues(bean.getAllContentTypes());
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6266265)

2020-10-01 08:33 UTC, rymsha commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    var bean = __.newBean('com.enonic.xp.lib.content.GetSiteHandler');
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6266264)

2020-10-01 08:33 UTC, rymsha commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    var bean = __.newBean('com.enonic.xp.lib.content.GetAttachmentsHandler');
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6266264)

2020-10-01 08:33 UTC, jsi commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    bean.aggregations = __.toScriptValue(params.aggregations);
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6266265)

2020-10-01 08:33 UTC, rymsha commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    var bean = __.newBean('com.enonic.xp.lib.content.GetOutboundDependenciesHandler');
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6266264)

2020-10-01 08:33 UTC, jsi commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    var bean = __.newBean('com.enonic.xp.lib.content.GetChildContentHandler');
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6266265)

2020-10-01 08:33 UTC, rymsha commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    return __.toNativeObjectIncludeNullValues(bean.getAllContentTypes());
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6266264)

2020-10-01 08:33 UTC, jsi commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    bean.contentTypes = __.toScriptValue(params.contentTypes);
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6266265)

2020-10-01 08:33 UTC, rymsha commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    var bean = __.newBean('com.enonic.xp.lib.content.ContentExistsHandler');
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6266264)

2020-10-01 08:33 UTC, jsi commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    return __.toNativeObjectIncludeNullValues(bean.getContentType());
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6266265)

2020-10-01 08:33 UTC, rymsha commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    return __.toNativeObjectIncludeNullValues(bean.getContentType());
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6266264)

2020-10-01 08:33 UTC, jsi commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    var value = params[name];
Codacy found an issue: [Variable Assigned to Object Injection Sink](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6266265)

2020-10-01 08:33 UTC, rymsha commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    bean.highlight = __.toScriptValue(params.highlight);
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6266264)

2020-10-01 08:33 UTC, jsi commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    var bean = __.newBean('com.enonic.xp.lib.content.GetSiteConfigHandler');
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6266265)

2020-10-01 08:33 UTC, rymsha commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    bean.filters = __.toScriptValue(params.filters);
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6266264)

2020-10-01 08:33 UTC, jsi commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    var bean = __.newBean('com.enonic.xp.lib.content.GetPermissionsHandler');
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6266265)

2020-10-01 08:33 UTC, rymsha commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    var bean = __.newBean('com.enonic.xp.lib.content.GetSiteConfigHandler');
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6266264)

2020-10-01 08:33 UTC, jsi commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    var bean = __.newBean('com.enonic.xp.lib.content.GetContentHandler');
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6266265)

2020-10-01 08:33 UTC, rymsha commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    var bean = __.newBean('com.enonic.xp.lib.content.GetAttachmentStreamHandler');
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6266264)

2020-10-01 08:33 UTC, jsi commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    var bean = __.newBean('com.enonic.xp.lib.content.GetAttachmentsHandler');
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6266265)

2020-10-01 08:33 UTC, rymsha commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    var bean = __.newBean('com.enonic.xp.lib.content.ContentTypeHandler');
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6266264)

2020-10-01 08:33 UTC, jsi commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    bean.filters = __.toScriptValue(params.filters);
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6266265)

2020-10-01 08:33 UTC, rymsha commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    var bean = __.newBean('com.enonic.xp.lib.content.QueryContentHandler');
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6266264)

2020-10-01 08:33 UTC, rymsha commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    var bean = __.newBean('com.enonic.xp.lib.content.GetChildContentHandler');
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6266264)

2020-10-01 08:33 UTC, jsi commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    var bean = __.newBean('com.enonic.xp.lib.content.GetOutboundDependenciesHandler');
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6266265)

2020-10-01 08:33 UTC, rymsha commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    var bean = __.newBean('com.enonic.xp.lib.content.GetContentHandler');
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6266264)

2020-10-01 08:33 UTC, jsi commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    return __.toNativeObjectIncludeNullValues(bean.execute());
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6266265)

2020-10-01 08:33 UTC, rymsha commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    return __.toNativeObjectIncludeNullValues(bean.execute());
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6266264)

2020-10-01 08:33 UTC, rymsha commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    bean.contentTypes = __.toScriptValue(params.contentTypes);
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6266264)

2020-10-01 08:33 UTC, rymsha commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    var bean = __.newBean('com.enonic.xp.lib.content.GetPermissionsHandler');
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6266264)

2020-10-01 08:33 UTC, rymsha commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    bean.aggregations = __.toScriptValue(params.aggregations);
Codacy found an issue: ['__' is not defined.](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6266264)

2020-10-01 09:01 UTC, jsi commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js  2
- modules/script/script-impl/src/main/java/com/enonic/xp/script/impl/util/ScriptMapGenerator.java  1
         

Clones added
============
- modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js  13
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6266265&bid=20402577)

2020-10-01 09:01 UTC, rymsha commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- modules/script/script-impl/src/main/java/com/enonic/xp/script/impl/util/ScriptMapGenerator.java  1
- modules/portal/portal-impl/src/test/java/com/enonic/xp/portal/impl/controller/PortalResponseSerializerTest.java  1
- modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js  2
         

Clones added
============
- modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js  13
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6266264&bid=20402576)

2020-10-01 09:01 UTC, jsi commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    var value = params[name];
Codacy found an issue: [Variable Assigned to Object Injection Sink](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6266265)

2020-10-01 09:01 UTC, rymsha commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    var value = params[name];
Codacy found an issue: [Variable Assigned to Object Injection Sink](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6266264)

2020-10-02 11:08 UTC, jsi commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js  2
- modules/script/script-impl/src/main/java/com/enonic/xp/script/impl/util/ScriptMapGenerator.java  1
         

Clones added
============
- modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js  13
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6266265&bid=20402577)

2020-10-02 11:08 UTC, jsi commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    var value = params[name];
Codacy found an issue: [Variable Assigned to Object Injection Sink](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6266265)

2020-10-02 11:09 UTC, rymsha commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- modules/script/script-impl/src/main/java/com/enonic/xp/script/impl/util/ScriptMapGenerator.java  1
- modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js  2
         

Clones added
============
- modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js  13
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6266264&bid=20402576)

2020-10-02 11:09 UTC, rymsha commented on modules/lib/lib-content/src/main/resources/lib/xp/content-graphql.js
> +    var value = params[name];
Codacy found an issue: [Variable Assigned to Object Injection Sink](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6266264)

2020-10-14 15:36 UTC, sigdestad requested changes
As discussed, I do not want to have presentation-specific things like this in the Core. If this should be fixed some where, it is in the framework (toNative..) or similar.

@rymsha any comments?

2020-10-14 16:21 UTC, rymsha commented
This PR won't be accepted in how it's made now. We need to discuss further

2020-10-14 16:52 UTC, rymsha commented
The main question here, why do we swallow null values in initial implementation?

2020-10-15 06:42 UTC, alansemenov commented
This issue was caused by [this](https://github.com/enonic/lib-guillotine/issues/65) and was fixed [here](https://github.com/enonic/starter-headless/pull/9), so this PR can be closed. We shouldn't swallow the null values but fixing this can cause side effects, so I suggest leaving it for now.

2020-10-15 06:50 UTC, closed without merging