Epic subroject refactoring
enonic/xp pull request #8450
Opened 2020-10-27 16:38 UTC by vbradnitski

2020-10-27 16:44 UTC, rymsha commented on modules/core/core-project/src/main/java/com/enonic/xp/core/impl/project/ProjectEvents.java
> +    public final static String CREATED_EVENT_TYPE = "project.created";
Codacy found an issue: ['static' modifier out of order with the JLS suggestions.](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6409742)

2020-10-27 16:44 UTC, rymsha commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 5
- Added 3
           

Coverage increased per file
===========================
+ modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/DuplicateContentCommand.java  1
+ modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/SetNodeChildOrderCommand.java  2
+ modules/core/core-project/src/main/java/com/enonic/xp/core/impl/project/ProjectServiceImpl.java  1
+ modules/core/core-api/src/main/java/com/enonic/xp/project/Project.java  1
+ modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/ProjectResource.java  1
+ modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/MoveNodeCommand.java  1
+ modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/MoveContentCommand.java  1
         

Coverage decreased per file
===========================
- modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/DuplicateNodeCommand.java  -1
- modules/core/core-api/src/main/java/com/enonic/xp/node/DuplicateNodeParams.java  -7
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/serializer/ContentDataSerializer.java  -6
- modules/core/core-api/src/main/java/com/enonic/xp/content/SetContentChildOrderParams.java  -8
- modules/core/core-api/src/main/java/com/enonic/xp/content/CreateContentTranslatorParams.java  -6
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/CreateNodeParamsFactory.java  -1
- modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/NodeEvents.java  -1
- modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/NodeServiceImpl.java  -2
- modules/core/core-api/src/main/java/com/enonic/xp/node/SetNodeChildOrderParams.java  -16
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/serializer/ComponentDataSerializerProvider.java  -1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/DuplicateContentProcessor.java  -8
- modules/core/core-api/src/main/java/com/enonic/xp/content/UpdateContentParams.java  -2
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResource.java  -1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentServiceImpl.java  -1
- modules/core/core-api/src/main/java/com/enonic/xp/content/ReorderChildContentsParams.java  -11
- modules/core/core-api/src/main/java/com/enonic/xp/content/Content.java  -1
- modules/core/core-api/src/main/java/com/enonic/xp/content/MoveContentParams.java  -3
- modules/core/core-api/src/main/java/com/enonic/xp/content/CreateContentParams.java  -9
- modules/core/core-api/src/main/java/com/enonic/xp/content/RenameContentParams.java  -7
         

Complexity increasing per file
==============================
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RenamedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectNotFoundException.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentEventSyncCommandParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ImportContentCommand.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentDataProcessor.java  5
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/serializer/ContentDataSerializer.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ManualOrderUpdatedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RestoreInitializedListener.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/UpdateContentCommand.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectContentEventListener.java  4
- modules/core/core-api/src/main/java/com/enonic/xp/content/ResetContentInheritParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/CreateNodeParamsFactory.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentProjectSyncTask.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/NameValueResolver.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SyncContentServiceImpl.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentContentSynchronizer.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/ProjectJson.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SetContentChildOrderProcessor.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/UpdatedEventSyncCommand.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/MoveContentProcessor.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/CreateProjectParamsJson.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/CreatedEventSyncCommand.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/DuplicateContentProcessor.java  1
- modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/storage/StoreMovedNodeParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentServiceImpl.java  1
- modules/core/core-api/src/main/java/com/enonic/xp/content/ImportContentResult.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentProjectSyncActivator.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentEventsSyncParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RenameContentProcessor.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentSyncParams.java  1
- modules/core/core-api/src/main/java/com/enonic/xp/content/ImportContentParams.java  5
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/ResetContentInheritJson.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/AbstractContentEventSyncCommand.java  2
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/ModifyProjectParamsJson.java  1
- modules/core/core-project/src/main/java/com/enonic/xp/core/impl/project/ProjectEvents.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/DeletedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ResetContentInheritanceCommand.java  7
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SortedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ImportContentFactory.java  2
- modules/core/core-api/src/main/java/com/enonic/xp/node/MoveNodeParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/MovedEventSyncCommand.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectEventListener.java  4
         

Clones added
============
- modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/project/ProjectResourceTest.java  4
- modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResourceTest.java  1
         

Clones removed
==============
+ modules/lib/lib-project/src/main/resources/lib/xp/project.js  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6409742&bid=20772830)

2020-10-27 16:44 UTC, rymsha commented on modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectContentEventListener.java
> +                    switch ( type )
Codacy found an issue: [Switch statements should have a default label](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6409742)

2020-10-27 16:44 UTC, rymsha commented on modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/NameValueResolver.java
> +        private NewName()
Codacy found an issue: [Avoid unnecessary constructors - the compiler will generate these for you](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6409742)

2020-10-27 16:44 UTC, jsi commented on modules/core/core-project/src/main/java/com/enonic/xp/core/impl/project/ProjectEvents.java
> +    public final static String CREATED_EVENT_TYPE = "project.created";
Codacy found an issue: ['static' modifier out of order with the JLS suggestions.](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6409740)

2020-10-27 16:44 UTC, jsi commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/storage/StoreMovedNodeParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/UpdateContentCommand.java  1
- modules/core/core-api/src/main/java/com/enonic/xp/content/ImportContentParams.java  5
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/NameValueResolver.java  4
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/ProjectJson.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectNotFoundException.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/ResetContentInheritJson.java  1
- modules/core/core-api/src/main/java/com/enonic/xp/content/ResetContentInheritParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentEventSyncCommandParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RenamedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentProjectSyncTask.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentServiceImpl.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/DuplicateContentProcessor.java  1
- modules/core/core-api/src/main/java/com/enonic/xp/content/ImportContentResult.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/MovedEventSyncCommand.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/CreatedEventSyncCommand.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SetContentChildOrderProcessor.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/MoveContentProcessor.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentSyncParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ImportContentFactory.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RestoreInitializedListener.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SyncContentServiceImpl.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/UpdatedEventSyncCommand.java  4
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/CreateProjectParamsJson.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectContentEventListener.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ManualOrderUpdatedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/CreateNodeParamsFactory.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ImportContentCommand.java  1
- modules/core/core-project/src/main/java/com/enonic/xp/core/impl/project/ProjectEvents.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectEventListener.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentContentSynchronizer.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentDataProcessor.java  5
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ResetContentInheritanceCommand.java  7
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/DeletedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/AbstractContentEventSyncCommand.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentProjectSyncActivator.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SortedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RenameContentProcessor.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/serializer/ContentDataSerializer.java  3
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/ModifyProjectParamsJson.java  1
- modules/core/core-api/src/main/java/com/enonic/xp/node/MoveNodeParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentEventsSyncParams.java  1
         

Clones removed
==============
+ modules/lib/lib-project/src/main/resources/lib/xp/project.js  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6409740&bid=20772829)

2020-10-27 19:56 UTC, rymsha commented on modules/core/core-api/src/main/java/com/enonic/xp/content/CreateContentParams.java
> +    private final boolean useParentLanguage;
Why would it be ever false?

2020-10-27 19:56 UTC, rymsha commented on modules/core/core-api/src/main/java/com/enonic/xp/content/CreateContentParams.java
> +    private final boolean createSiteTemplateFolder;
This is too specific for site

2020-10-27 19:56 UTC, rymsha commented on modules/core/core-api/src/main/java/com/enonic/xp/content/CreateContentParams.java
> +    private final Set<ContentInheritType> inherit;
Can we create with specific flags inset?

2020-10-27 19:56 UTC, rymsha commented on modules/core/core-api/src/main/java/com/enonic/xp/content/CreateContentParams.java
> +    private final Page page;
Content should not depend on Page

2020-10-27 19:56 UTC, rymsha commented on modules/core/core-api/src/main/java/com/enonic/xp/content/ImportContentResult.java
> +    public boolean isPreExisting()
What does it mean?

2020-10-27 19:56 UTC, rymsha commented on modules/core/core-api/src/main/java/com/enonic/xp/content/MoveContentParams.java
> +    private boolean stopInherit;
When is it false?

2020-10-27 19:56 UTC, rymsha commented on modules/core/core-api/src/main/java/com/enonic/xp/content/SyncContentService.java
> +    void restoreInheritance( final ResetContentInheritParams params );
Reset/restore. We should choose

2020-10-27 19:56 UTC, rymsha commented on modules/core/core-api/src/main/java/com/enonic/xp/node/DuplicateNodeParams.java
> +    @Deprecated
Make sure deprecated are not in use

2020-10-27 19:56 UTC, rymsha commented on modules/core/core-api/src/main/java/com/enonic/xp/node/NodeDataProcessor.java
> +    PropertyTree process( final PropertyTree originalData );
It implies PropertyTree is immutable.
It is not the case

2020-10-28 09:08 UTC, rymsha requested changes

2020-10-28 11:35 UTC, rymsha requested changes

2020-10-28 13:31 UTC, jsi commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/MovedEventSyncCommand.java  2
- modules/core/core-project/src/main/java/com/enonic/xp/core/impl/project/ProjectEvents.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ManualOrderUpdatedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/UpdatedEventSyncCommand.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/CreatedEventSyncCommand.java  2
- modules/core/core-api/src/main/java/com/enonic/xp/content/ImportContentParams.java  5
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/serializer/ContentDataSerializer.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SortedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentServiceImpl.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/ModifyProjectParamsJson.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentContentSynchronizer.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectContentEventListener.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SyncContentServiceImpl.java  1
- modules/core/core-api/src/main/java/com/enonic/xp/content/ResetContentInheritParams.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/ResetContentInheritJson.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/DuplicateContentProcessor.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentProjectSyncTask.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentSyncParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/UpdateContentCommand.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/NameValueResolver.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentEventsSyncParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ImportContentCommand.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentProjectSyncActivator.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SetContentChildOrderProcessor.java  1
- modules/core/core-api/src/main/java/com/enonic/xp/content/ImportContentResult.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectNotFoundException.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentEventSyncCommandParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ResetContentInheritanceCommand.java  7
- modules/core/core-api/src/main/java/com/enonic/xp/node/MoveNodeParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RenamedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/MoveContentProcessor.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RenameContentProcessor.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/ProjectJson.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/AbstractContentEventSyncCommand.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/CreateNodeParamsFactory.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/DeletedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RestoreInitializedListener.java  2
- modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/storage/StoreMovedNodeParams.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/CreateProjectParamsJson.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectEventListener.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ImportContentFactory.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentDataProcessor.java  5
         

Clones removed
==============
+ modules/lib/lib-project/src/main/resources/lib/xp/project.js  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6409740&bid=20772829)

2020-10-28 13:33 UTC, rymsha commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 5
- Added 1
           

Complexity increasing per file
==============================
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentServiceImpl.java  1
- modules/core/core-api/src/main/java/com/enonic/xp/content/ImportContentResult.java  1
- modules/core/core-api/src/main/java/com/enonic/xp/node/MoveNodeParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/UpdatedEventSyncCommand.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/AbstractContentEventSyncCommand.java  2
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/ResetContentInheritJson.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/ModifyProjectParamsJson.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ImportContentFactory.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RenamedEventSyncCommand.java  3
- modules/core/core-api/src/main/java/com/enonic/xp/content/ResetContentInheritParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentContentSynchronizer.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentSyncParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/CreatedEventSyncCommand.java  2
- modules/core/core-project/src/main/java/com/enonic/xp/core/impl/project/ProjectEvents.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentEventsSyncParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ImportContentCommand.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentProjectSyncActivator.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RenameContentProcessor.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/DeletedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentDataProcessor.java  5
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SortedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/CreateNodeParamsFactory.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ResetContentInheritanceCommand.java  7
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RestoreInitializedListener.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/NameValueResolver.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SetContentChildOrderProcessor.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectNotFoundException.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectEventListener.java  4
- modules/core/core-api/src/main/java/com/enonic/xp/content/ImportContentParams.java  5
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentProjectSyncTask.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ManualOrderUpdatedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/MoveContentProcessor.java  1
- modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/storage/StoreMovedNodeParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/serializer/ContentDataSerializer.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/UpdateContentCommand.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SyncContentServiceImpl.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/CreateProjectParamsJson.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/DuplicateContentProcessor.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentEventSyncCommandParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectContentEventListener.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/MovedEventSyncCommand.java  2
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/ProjectJson.java  2
         

Clones added
============
- modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/project/ProjectResourceTest.java  4
- modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResourceTest.java  1
         

Clones removed
==============
+ modules/lib/lib-project/src/main/resources/lib/xp/project.js  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6409742&bid=20772830)

2020-10-28 13:34 UTC, rymsha commented on modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectContentEventListener.java
> +                    switch ( type )
Codacy found an issue: [Switch statements should have a default label](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6409742)

2020-10-28 14:12 UTC, jsi commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/ResetContentInheritJson.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectContentEventListener.java  4
- modules/core/core-api/src/main/java/com/enonic/xp/content/ImportContentParams.java  5
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentContentSynchronizer.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/ProjectJson.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ResetContentInheritanceCommand.java  7
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SetContentChildOrderProcessor.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/UpdatedEventSyncCommand.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/serializer/ContentDataSerializer.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/MovedEventSyncCommand.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentSyncParams.java  1
- modules/core/core-api/src/main/java/com/enonic/xp/content/ResetContentInheritParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/CreatedEventSyncCommand.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentServiceImpl.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SortedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ImportContentCommand.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/AbstractContentEventSyncCommand.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentProjectSyncActivator.java  2
- modules/core/core-api/src/main/java/com/enonic/xp/node/MoveNodeParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ManualOrderUpdatedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectNotFoundException.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SyncContentServiceImpl.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/CreateNodeParamsFactory.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/MoveContentProcessor.java  1
- modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/storage/StoreMovedNodeParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/UpdateContentCommand.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RenameContentProcessor.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentProjectSyncTask.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentDataProcessor.java  5
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentEventSyncCommandParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RenamedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ImportContentFactory.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/DuplicateContentProcessor.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/CreateProjectParamsJson.java  3
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/ModifyProjectParamsJson.java  1
- modules/core/core-api/src/main/java/com/enonic/xp/content/ImportContentResult.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentEventsSyncParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RestoreInitializedListener.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectEventListener.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/NameValueResolver.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/DeletedEventSyncCommand.java  3
- modules/core/core-project/src/main/java/com/enonic/xp/core/impl/project/ProjectEvents.java  1
         

Clones removed
==============
+ modules/lib/lib-project/src/main/resources/lib/xp/project.js  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6409740&bid=20772829)

2020-10-28 14:12 UTC, rymsha commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 5
- Added 1
           

Complexity increasing per file
==============================
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentServiceImpl.java  1
- modules/core/core-api/src/main/java/com/enonic/xp/node/MoveNodeParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RestoreInitializedListener.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/UpdatedEventSyncCommand.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentDataProcessor.java  5
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SetContentChildOrderProcessor.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/DuplicateContentProcessor.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ImportContentFactory.java  2
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/CreateProjectParamsJson.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/serializer/ContentDataSerializer.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentEventSyncCommandParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentContentSynchronizer.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentSyncParams.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/ModifyProjectParamsJson.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/CreatedEventSyncCommand.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectContentEventListener.java  4
- modules/core/core-api/src/main/java/com/enonic/xp/content/ImportContentParams.java  5
- modules/core/core-project/src/main/java/com/enonic/xp/core/impl/project/ProjectEvents.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentProjectSyncTask.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RenameContentProcessor.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ImportContentCommand.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SortedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/MoveContentProcessor.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentProjectSyncActivator.java  2
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/ProjectJson.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/MovedEventSyncCommand.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RenamedEventSyncCommand.java  3
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/ResetContentInheritJson.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/CreateNodeParamsFactory.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/NameValueResolver.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/AbstractContentEventSyncCommand.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ManualOrderUpdatedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentEventsSyncParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/DeletedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectNotFoundException.java  1
- modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/storage/StoreMovedNodeParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectEventListener.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ResetContentInheritanceCommand.java  7
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SyncContentServiceImpl.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/UpdateContentCommand.java  1
- modules/core/core-api/src/main/java/com/enonic/xp/content/ResetContentInheritParams.java  1
- modules/core/core-api/src/main/java/com/enonic/xp/content/ImportContentResult.java  1
         

Clones added
============
- modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResourceTest.java  1
- modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/project/ProjectResourceTest.java  4
         

Clones removed
==============
+ modules/lib/lib-project/src/main/resources/lib/xp/project.js  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6409742&bid=20772830)

2020-10-28 14:12 UTC, rymsha commented on modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectContentEventListener.java
> +                    switch ( type )
Codacy found an issue: [Switch statements should have a default label](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6409742)

2020-10-28 14:40 UTC, jsi commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/core/core-api/src/main/java/com/enonic/xp/content/ResetContentInheritParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ImportContentCommand.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/UpdateContentCommand.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SyncContentServiceImpl.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SetContentChildOrderProcessor.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/DuplicateContentProcessor.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/DeletedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RenamedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/serializer/ContentDataSerializer.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentEventSyncCommandParams.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/ModifyProjectParamsJson.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/ProjectJson.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentEventsSyncParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentProjectSyncActivator.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentProjectSyncTask.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/UpdatedEventSyncCommand.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/MoveContentProcessor.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ImportContentFactory.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectNotFoundException.java  1
- modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/storage/StoreMovedNodeParams.java  1
- modules/core/core-project/src/main/java/com/enonic/xp/core/impl/project/ProjectEvents.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/ResetContentInheritJson.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentServiceImpl.java  1
- modules/core/core-api/src/main/java/com/enonic/xp/content/ImportContentResult.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/CreatedEventSyncCommand.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/AbstractContentEventSyncCommand.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentSyncParams.java  1
- modules/core/core-api/src/main/java/com/enonic/xp/node/MoveNodeParams.java  1
- modules/core/core-api/src/main/java/com/enonic/xp/content/ImportContentParams.java  5
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectEventListener.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/NameValueResolver.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/MovedEventSyncCommand.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RestoreInitializedListener.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectContentEventListener.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ManualOrderUpdatedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SortedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RenameContentProcessor.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ResetContentInheritanceCommand.java  7
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentDataProcessor.java  5
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentContentSynchronizer.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/CreateProjectParamsJson.java  3
         

Clones removed
==============
+ modules/lib/lib-project/src/main/resources/lib/xp/project.js  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6409740&bid=20772829)

2020-10-28 14:52 UTC, jsi commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectEventListener.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentProjectSyncActivator.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/CreatedEventSyncCommand.java  2
- modules/core/core-api/src/main/java/com/enonic/xp/content/ResetContentInheritParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/MoveContentProcessor.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/NameValueResolver.java  4
- modules/core/core-project/src/main/java/com/enonic/xp/core/impl/project/ProjectEvents.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ImportContentFactory.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentEventsSyncParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/serializer/ContentDataSerializer.java  2
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/ProjectJson.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ResetContentInheritanceCommand.java  7
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/DuplicateContentProcessor.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentSyncParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentDataProcessor.java  5
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SortedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SetContentChildOrderProcessor.java  1
- modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/storage/StoreMovedNodeParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/AbstractContentEventSyncCommand.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RenameContentProcessor.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/ResetContentInheritJson.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectNotFoundException.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/ModifyProjectParamsJson.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ImportContentCommand.java  1
- modules/core/core-api/src/main/java/com/enonic/xp/node/MoveNodeParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentContentSynchronizer.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentEventSyncCommandParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ManualOrderUpdatedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/UpdateContentCommand.java  1
- modules/core/core-api/src/main/java/com/enonic/xp/content/ImportContentParams.java  5
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/MovedEventSyncCommand.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/UpdatedEventSyncCommand.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RenamedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/DeletedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentServiceImpl.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RestoreInitializedListener.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectContentEventListener.java  3
- modules/core/core-api/src/main/java/com/enonic/xp/content/ImportContentResult.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/CreateProjectParamsJson.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentProjectSyncTask.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SyncContentServiceImpl.java  1
         

Clones removed
==============
+ modules/lib/lib-project/src/main/resources/lib/xp/project.js  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6409740&bid=20772829)

2020-10-28 14:55 UTC, rymsha commented on modules/core/core-content/src/test/java/com/enonic/xp/core/impl/content/MoveContentCommandTest.java
> +    private final XDataService xDataService = Mockito.mock( XDataService.class );
Codacy found an issue: [Avoid unused private fields such as 'xDataService'.](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6409742)

2020-10-28 14:55 UTC, rymsha commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 5
- Added 1
           

Complexity increasing per file
==============================
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/serializer/ContentDataSerializer.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/DeletedEventSyncCommand.java  3
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/ModifyProjectParamsJson.java  1
- modules/core/core-project/src/main/java/com/enonic/xp/core/impl/project/ProjectEvents.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/UpdateContentCommand.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/NameValueResolver.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentServiceImpl.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ImportContentFactory.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SetContentChildOrderProcessor.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SyncContentServiceImpl.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ResetContentInheritanceCommand.java  7
- modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/storage/StoreMovedNodeParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RenameContentProcessor.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentDataProcessor.java  5
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentEventsSyncParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/MoveContentProcessor.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentProjectSyncActivator.java  3
- modules/core/core-api/src/main/java/com/enonic/xp/node/MoveNodeParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentSyncParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentContentSynchronizer.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/ProjectJson.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/MovedEventSyncCommand.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SortedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectContentEventListener.java  3
- modules/core/core-api/src/main/java/com/enonic/xp/content/ImportContentParams.java  5
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ManualOrderUpdatedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/DuplicateContentProcessor.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/ResetContentInheritJson.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RenamedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectEventListener.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentEventSyncCommandParams.java  1
- modules/core/core-api/src/main/java/com/enonic/xp/content/ResetContentInheritParams.java  1
- modules/core/core-api/src/main/java/com/enonic/xp/content/ImportContentResult.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/AbstractContentEventSyncCommand.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectNotFoundException.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/CreateProjectParamsJson.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RestoreInitializedListener.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentProjectSyncTask.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ImportContentCommand.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/CreatedEventSyncCommand.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/UpdatedEventSyncCommand.java  4
         

Clones added
============
- modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/project/ProjectResourceTest.java  4
- modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResourceTest.java  1
         

Clones removed
==============
+ modules/lib/lib-project/src/main/resources/lib/xp/project.js  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6409742&bid=20772830)

2020-10-29 07:10 UTC, jsi commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ImportContentCommand.java  1
- modules/core/core-api/src/main/java/com/enonic/xp/content/ImportContentResult.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/UpdateContentCommand.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentContentSynchronizer.java  1
- modules/core/core-api/src/main/java/com/enonic/xp/content/ImportContentParams.java  5
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentSyncParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentEventSyncCommandParams.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/ProjectJson.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/NameValueResolver.java  4
- modules/core/core-api/src/main/java/com/enonic/xp/node/MoveNodeParams.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/ResetContentInheritJson.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SortedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RestoreInitializedListener.java  2
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/CreateProjectParamsJson.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ResetContentInheritanceCommand.java  7
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/DeletedEventSyncCommand.java  3
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/ModifyProjectParamsJson.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RenameContentProcessor.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentDataProcessor.java  5
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RenamedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SyncContentServiceImpl.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectEventListener.java  4
- modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/storage/StoreMovedNodeParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/DuplicateContentProcessor.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/UpdatedEventSyncCommand.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/MoveContentProcessor.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentProjectSyncActivator.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectNotFoundException.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/AbstractContentEventSyncCommand.java  2
- modules/core/core-project/src/main/java/com/enonic/xp/core/impl/project/ProjectEvents.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectContentEventListener.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentEventsSyncParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/MovedEventSyncCommand.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SetContentChildOrderProcessor.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentProjectSyncTask.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentServiceImpl.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/CreatedEventSyncCommand.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/serializer/ContentDataSerializer.java  2
- modules/core/core-api/src/main/java/com/enonic/xp/content/ResetContentInheritParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ImportContentFactory.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ManualOrderUpdatedEventSyncCommand.java  3
         

Clones removed
==============
+ modules/lib/lib-project/src/main/resources/lib/xp/project.js  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/enonic/xp/pullRequest?prid=6409740&bid=20772829)

2020-10-29 07:11 UTC, rymsha commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 5
           

Complexity increasing per file
==============================
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/ProjectJson.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/UpdatedEventSyncCommand.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/DuplicateContentProcessor.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentSyncParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/UpdateContentCommand.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RestoreInitializedListener.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentDataProcessor.java  5
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RenamedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentContentSynchronizer.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ImportContentFactory.java  2
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/ModifyProjectParamsJson.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/RenameContentProcessor.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ImportContentCommand.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentProjectSyncTask.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ResetContentInheritanceCommand.java  7
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/AbstractContentEventSyncCommand.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentEventSyncCommandParams.java  1
- modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/storage/StoreMovedNodeParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentProjectSyncActivator.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/DeletedEventSyncCommand.java  3
- modules/core/core-api/src/main/java/com/enonic/xp/content/ResetContentInheritParams.java  1
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/project/json/CreateProjectParamsJson.java  3
- modules/core/core-api/src/main/java/com/enonic/xp/node/MoveNodeParams.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectEventListener.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/MoveContentProcessor.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SortedEventSyncCommand.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectNotFoundException.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/NameValueResolver.java  4
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/serializer/ContentDataSerializer.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentServiceImpl.java  1
- modules/core/core-api/src/main/java/com/enonic/xp/content/ImportContentResult.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SetContentChildOrderProcessor.java  1
- modules/core/core-project/src/main/java/com/enonic/xp/core/impl/project/ProjectEvents.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ProjectContentEventListener.java  3
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/MovedEventSyncCommand.java  2
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ManualOrderUpdatedEventSyncCommand.java  3
- modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/ResetContentInheritJson.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ContentEventsSyncParams.java  1
- modules/core/core-api/src/main/java/com/enonic/xp/content/ImportContentParams.java  5
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SyncContentServiceImpl.java  1
- modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/CreatedEventSyncCommand.java  2
         

Clones added
============
- modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/project/ProjectResourceTest.java  4
- modules/admin/admin-impl/src/test/java/com/enonic/xp/admin/impl/rest/resource/content/ContentResourceTest.java  1
         

Clones removed
==============
+ modules/lib/lib-project/src/main/resources/lib/xp/project.js  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=6409742&bid=20772830)

2020-11-04 08:43 UTC, closed without merging