Add `originProject` field to /content and /list API response #8504
enonic/xp pull request #8505
Opened 2020-11-25 13:40 UTC by ashklianko

2020-11-25 13:43 UTC, anatol-sialitski approved these changes

2020-11-25 14:43 UTC, rymsha requested changes
test missing where originProject is not null

2020-11-26 06:59 UTC, ashklianko commented
> test missing where originProject is not null

Updated

2020-11-26 07:46 UTC, rymsha approved these changes

2020-11-26 08:13 UTC, vbradnitski approved these changes

2020-11-26 08:13 UTC, merged