Anonymous audit-log events #8511
enonic/xp pull request #8531
Opened 2020-12-07 14:54 UTC by anatol-sialitski

2020-12-07 14:57 UTC, rymsha requested changes

2020-12-07 14:57 UTC, rymsha commented on modules/admin/admin-impl/src/main/java/com/enonic/xp/admin/impl/rest/resource/content/json/UpdateContentJson.java
> +            modifier( modifier ).
Do we use this field at all? We should not, probably as we should not trust the caller.

2020-12-07 16:08 UTC, rymsha requested changes

2020-12-07 16:08 UTC, rymsha commented on modules/core/core-api/src/main/java/com/enonic/xp/content/UpdateContentParams.java
>          this.modifier = modifier;
```suggestion
```

2020-12-07 16:09 UTC, rymsha commented on modules/core/core-api/src/main/java/com/enonic/xp/content/UpdateContentParams.java
>          this.modifier = modifier;
And all unused private fields should be deleted as well

2020-12-08 08:46 UTC, rymsha approved these changes

2020-12-08 08:49 UTC, vbradnitski approved these changes

2020-12-08 09:03 UTC, merged