The underscore path returns the main page #8148
enonic/xp pull request #8554
Opened 2020-12-14 19:44 UTC by anatol-sialitski

2020-12-14 21:32 UTC, rymsha commented on modules/web/web-api/src/main/java/com/enonic/xp/web/handler/BaseWebHandler.java
>      private EnumSet<HttpMethod> methodsAllowed;
Also final

2020-12-14 21:33 UTC, rymsha commented on modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/handler/unknown/UnknownEndpointHandler.java
> +        return 1;
Test it. It should be greater than default

2020-12-14 21:33 UTC, rymsha approved these changes

2020-12-15 07:16 UTC, rymsha requested changes

2020-12-15 07:16 UTC, rymsha commented on modules/web/web-api/src/main/java/com/enonic/xp/web/handler/BaseWebHandler.java
> +    public static final int DEFAULT_ORDER = 0;
don't extend public API for test s only.

2020-12-15 07:40 UTC, rymsha approved these changes

2020-12-15 11:08 UTC, vbradnitski approved these changes

2020-12-15 11:49 UTC, merged