Task for project or layer create/update #8443
enonic/xp pull request #8563
Opened 2020-12-18 14:49 UTC by vbradnitski

2020-12-18 16:18 UTC, rymsha requested changes

2020-12-18 16:18 UTC, rymsha commented on modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentContentSynchronizer.java
> +    public Context sourceContext;
```suggestion
```

2020-12-18 16:18 UTC, rymsha commented on modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/ParentContentSynchronizer.java
> +    private Context targetContext;
```suggestion
```

2020-12-18 16:18 UTC, rymsha commented on modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/SyncContentServiceImpl.java
> +
```suggestion
@Override
```

2020-12-18 16:18 UTC, rymsha commented on modules/core/core-api/src/main/java/com/enonic/xp/content/ProjectSyncParams.java
> +    private final ProjectName sourceProject;
I am not sure source project should be here.
1. It allows to sync content from any project
2. It does not fit into muli-inheritance 

Service should get sourceProject(s) from project data

`targetProject` should be called just `project`

2020-12-18 16:18 UTC, rymsha commented on modules/itest/itest-core/src/test/java/com/enonic/xp/core/content/ProjectEventListenerTest.java
> +   /* @Test
remove

2020-12-18 16:18 UTC, rymsha commented on modules/server/server-rest/src/main/java/com/enonic/xp/impl/server/rest/task/ProjectsSyncTask.java
> +    private Context createAdminContext()
Maybe transfer task caller context, so it is not always "su"?

2020-12-21 12:00 UTC, rymsha commented on modules/itest/itest-core/build.gradle
> +    testFixturesImplementation(testFixtures( project( ":core:core-task" ) ))
```suggestion
    testImplementation(testFixtures( project( ":core:core-task" ) ))
```

2020-12-21 12:03 UTC, rymsha commented on modules/server/server-rest/src/main/java/com/enonic/xp/impl/server/rest/ProjectResource.java
> +    @Path("syncAll")
Write a doc

2020-12-21 12:03 UTC, rymsha approved these changes

2020-12-21 14:07 UTC, rymsha approved these changes

2020-12-21 14:58 UTC, anatol-sialitski approved these changes

2020-12-21 15:03 UTC, merged