treeSelectorQuery uses deprecated method after performance fix  #8577
enonic/xp pull request #8595
Opened 2021-01-06 15:36 UTC by vbradnitski

2021-01-06 17:16 UTC, rymsha commented on modules/core/core-api/src/main/java/com/enonic/xp/node/NodeHits.java
> +            filter( Objects::nonNull ).
I would prefer NPE here instead, because it is incorrect to not request paths, and ask for them later

2021-01-07 16:59 UTC, rymsha approved these changes

2021-01-08 06:51 UTC, anatol-sialitski approved these changes

2021-01-08 08:08 UTC, rymsha requested changes

2021-01-08 08:08 UTC, rymsha commented on modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/search/NodeSearchServiceImpl.java
> +            returnFields( query.isWithPath() ? ReturnFields.create().
I don't currently imagine any other fields but `path` to be requested. Maybe we should deprecate/remove the method and move building of `ReturnFields` higher up

2021-01-08 16:09 UTC, rymsha commented on modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/search/NodeSearchServiceImpl.java
> +            returnFields( query.isWithPath() ? ReturnFields.create().
there is also a request for REFERENCE filed. we need to keep it as it is for now

2021-01-08 16:09 UTC, rymsha approved these changes

2021-01-08 16:10 UTC, merged