repo.create fails if permissions doesn't have deny:[] #6794
enonic/xp pull request #8710
Opened 2021-03-19 13:46 UTC by anatol-sialitski

2021-03-19 16:00 UTC, rymsha requested changes
That would also make `allow` optional. Is it intentional?

2021-03-22 07:47 UTC, anatol-sialitski commented
> That would also make `allow` optional. Is it intentional?

@rymsha Yes, the previous implementation supports creation a repo with empty `allow` permission. But, if skip `allow` in params, then will be the same error as with `deny`. So I use the resolvePermissions for both fields.

2021-03-22 08:00 UTC, rymsha approved these changes

2021-03-22 08:03 UTC, vbradnitski approved these changes

2021-03-22 11:52 UTC, merged