Epic scheduler
enonic/xp pull request #8730
Opened 2021-04-07 11:01 UTC by vbradnitski

2021-04-07 14:54 UTC, rymsha requested changes

2021-04-07 14:54 UTC, rymsha commented on modules/runtime/src/home/config/com.enonic.xp.scheduler.cfg
> +#job.myjob.enabled=true
it probably should be clean file (for now)
we don't give examples in files, but show default valuse

2021-04-07 14:54 UTC, rymsha commented on modules/core/core-scheduler/src/main/java/com/enonic/xp/impl/scheduler/serializer/SchedulerSerializer.java
> +public class SchedulerSerializer
add private ctor

2021-04-07 14:54 UTC, rymsha commented on modules/core/core-api/src/main/java/com/enonic/xp/scheduler/SchedulerName.java
> +public final class SchedulerName
ScheduledJobName

2021-04-07 18:07 UTC, rymsha approved these changes

2021-04-08 06:25 UTC, anatol-sialitski approved these changes

2021-04-08 09:02 UTC, merged