Add job to clean up audit log #8439
enonic/xp pull request #8739
Opened 2021-04-09 13:56 UTC by vbradnitski

2021-04-09 14:12 UTC, rymsha requested changes

2021-04-09 14:12 UTC, rymsha commented on modules/app/app-system/src/main/java/com/enonic/xp/app/system/AuditLogCleanUpHandler.java
> +            if ( count % batchSize == 0 )
if batch size is 0 (never set for some reason) debug logs may explode

2021-04-09 14:12 UTC, rymsha commented on modules/app/app-system/src/main/java/com/enonic/xp/app/system/AuditLogCleanUpHandler.java
> +            LOG.info( "Audit log clean up started." );
don't use "." in single sentence log message

2021-04-09 14:12 UTC, rymsha commented on modules/app/app-system/src/main/resources/tasks/auditLogCleanUp/auditLogCleanUp.js
> +exports.run = function () {
file/folder name should be `audit-log-cleanup`

2021-04-09 14:12 UTC, rymsha commented on modules/core/core-api/src/main/java/com/enonic/xp/audit/CleanUpAuditLogParams.java
> +public class CleanUpAuditLogParams
```suggestion
public final class CleanUpAuditLogParams
```

2021-04-09 14:12 UTC, rymsha commented on modules/app/app-system/src/main/resources/tasks/auditLogCleanUp/auditLogCleanUp.xml
> +  <form>
it should be possible to specify threshold here (but job should not specify anything)

2021-04-09 14:12 UTC, rymsha commented on modules/core/core-audit/src/main/java/com/enonic/xp/core/impl/audit/CleanUpAuditLogCommand.java
> +        return AuditLogContext.createContext().callWith( this::doCleanUp );
if `until` is `Instant.EPOCH` just add a debug log, that cleanup won't be done.

2021-04-09 14:42 UTC, rymsha requested changes

2021-04-09 14:42 UTC, rymsha commented on modules/core/core-api/src/main/java/com/enonic/xp/audit/CleanUpAuditLogResult.java
> +public class CleanUpAuditLogResult
```suggestion
public final class CleanUpAuditLogResult
```

2021-04-10 21:25 UTC, rymsha commented on modules/core/core-scheduler/src/main/resources/com/enonic/xp/impl/scheduler/default.properties
> +job.audit.calendar.timezone=GMT+2:00
It would be daytime in some areas. We may need to find a way to specify "local time"

2021-04-12 11:49 UTC, rymsha approved these changes

2021-04-12 11:59 UTC, anatol-sialitski approved these changes

2021-04-12 13:03 UTC, merged