contextLib: setting contentRootPath leads to an error #9228
enonic/xp pull request #9233
Opened 2021-11-23 14:27 UTC by vbradnitski

2021-11-23 14:44 UTC, rymsha approved these changes

2021-11-23 15:02 UTC, anatol-sialitski commented on modules/lib/lib-content/src/main/resources/lib/xp/content.js
> +exports.CONTENT_ROOT_PATH = com.enonic.xp.content.ContentConstants.CONTENT_ROOT_PATH;
I don't like that approach I would prefer to use helper for constants. But it works so I approve pr.

2021-11-23 15:03 UTC, anatol-sialitski approved these changes

2021-11-23 15:07 UTC, rymsha requested changes
add test and example

2021-11-24 10:54 UTC, rymsha approved these changes

2021-11-24 10:58 UTC, merged