Duplicate of a content is inherited in layer without child elements #…
enonic/xp pull request #9240
Opened 2021-11-24 15:17 UTC by vbradnitski

…9239

2021-11-27 11:07 UTC, rymsha requested changes

2021-11-27 11:07 UTC, rymsha commented on modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/NodeServiceImpl.java
> +        this.eventPublisher.publish( NodeEvents.duplicated( result.getNode() ) );
Isn't in the idea that duplicated event contains all duplicated node ids?

2021-11-29 12:42 UTC, rymsha approved these changes

2021-11-29 12:54 UTC, anatol-sialitski approved these changes

2021-11-29 13:45 UTC, merged