ResourceService should be able to load data from nodes #9346
enonic/xp pull request #9364
Opened 2022-02-11 13:59 UTC by vbradnitski

2022-02-11 16:41 UTC, rymsha approved these changes

2022-02-14 15:59 UTC, rymsha requested changes

2022-02-14 15:59 UTC, rymsha commented on modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/resource/ResourceServiceImpl.java
> +    private ValueResource findProjectResource( final ResourceKey key )
this method goes to `NodeResourceApplicationUrlResolver`

2022-02-14 17:16 UTC, sigdestad commented
Just a thought, how about shredding these files to disk and load resources from there?

2022-02-18 14:12 UTC, rymsha commented on modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/resolver/NodeResourceApplicationUrlResolver.java
> +            final FindNodesByQueryResult nodes = this.nodeService.findByQuery( NodeQuery.create()
Maybe use DSL?

2022-02-23 11:39 UTC, rymsha approved these changes

2022-02-23 11:39 UTC, merged