Dynamic Schema API #9391
enonic/xp pull request #9393
Opened 2022-03-14 14:57 UTC by vbradnitski

2022-03-14 15:20 UTC, anatol-sialitski commented on modules/core/core-api/src/main/java/com/enonic/xp/resource/CreateDynamicSchemaParams.java
> +            Preconditions.checkNotNull( key, "type must be set" );
`type` instead of `key`

2022-03-14 15:20 UTC, anatol-sialitski commented on modules/core/core-api/src/main/java/com/enonic/xp/resource/DeleteDynamicSchemaParams.java
> +            Preconditions.checkNotNull( key, "type must be set" );
`type` instead of `key`

2022-03-14 15:22 UTC, anatol-sialitski commented on modules/core/core-api/src/main/java/com/enonic/xp/resource/GetDynamicSchemaParams.java
> +            Preconditions.checkNotNull( key, "type must be set" );
`type` instead of `key`

2022-03-14 15:23 UTC, rymsha requested changes

2022-03-14 15:26 UTC, anatol-sialitski commented on modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/DynamicSchemaServiceImpl.java
> +
validation is missing :)

2022-03-15 08:29 UTC, rymsha approved these changes

2022-03-15 08:34 UTC, merged