Register principal actions in Audit Log #9319
enonic/xp pull request #9399
Opened 2022-03-15 19:38 UTC by anatol-sialitski

2022-03-15 21:08 UTC, rymsha commented on modules/core/core-security/src/main/java/com/enonic/xp/core/impl/security/SecurityAuditLogSupportImpl.java
> +        log( "system.idProvider.update", data, AuditLogUris.from( params.getKey().toString() ), rootContext );
role.update ?

2022-03-18 12:08 UTC, rymsha approved these changes

2022-03-18 12:12 UTC, vbradnitski approved these changes

2022-03-18 12:13 UTC, rymsha requested changes
fix

2022-03-18 14:37 UTC, rymsha approved these changes

2022-03-29 16:56 UTC, rymsha commented on modules/core/core-security/src/main/java/com/enonic/xp/core/impl/security/SecurityAuditLogSupportImpl.java
> +            PropertySet paramsSet = data.addSet( "params" );
See above

2022-03-30 10:32 UTC, rymsha approved these changes

2022-03-30 10:52 UTC, merged