SharedMap js API #9443
enonic/xp pull request #9495
Opened 2022-06-07 07:30 UTC by anatol-sialitski

2022-06-07 08:50 UTC, rymsha requested changes

2022-06-07 08:50 UTC, rymsha commented on modules/lib/lib-grid/build.gradle
> +    testRuntimeOnly "org.junit.vintage:junit-vintage-engine:${junitJupiterVersion}"
```suggestion
```

we must not use Junit4 in XP tests

2022-06-07 08:50 UTC, rymsha commented on modules/lib/lib-grid/src/main/java/com/enonic/xp/lib/grid/MemoryGridHelper.java
> +public class MemoryGridHelper
I think we call them `Handler` in most of the places

2022-06-07 08:50 UTC, rymsha commented on modules/lib/lib-grid/src/main/resources/lib/xp/grid.js
> +    checkRequired(params, 'mapId');
It would be more convenient to get a map by `mapId` just once and work with it implicitly (similar to how `RepoConnection` in node api works)

2022-06-07 10:58 UTC, rymsha commented on modules/lib/lib-grid/src/main/resources/lib/xp/grid.js
> +function MemoryGrid(mapId) {
it should be `SharedMemory` class (despite being in lb-gid)

2022-06-14 08:18 UTC, alansemenov commented on modules/lib/lib-grid/src/test/resources/test/grid-test.js
> +        assert.assertEquals(`Parameter "func" is required`, e);
Codacy has a fix for the issue: [Strings must use singlequote.](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=9567561)
```suggestion
        assert.assertEquals('Parameter "func" is required', e);
```

2022-06-14 08:18 UTC, alansemenov commented on modules/lib/lib-grid/src/test/resources/test/grid-test.js
> +        assert.assertEquals(`Parameter "key" is required`, e);
Codacy has a fix for the issue: [Strings must use singlequote.](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=9567561)
```suggestion
        assert.assertEquals('Parameter "key" is required', e);
```

2022-06-14 09:06 UTC, rymsha commented on modules/lib/lib-grid/src/main/resources/lib/xp/grid.js
> + * WARNING: key and value of the map can only be standard Java classes
```suggestion
 * WARNING: Due to distributed nature of the Shared Map not all types of keys and values can be used. Strings, numbers and pure JSON objects are supported. There is no runtime check for type compatibility due to performance reasons. It is also developer's responsibility to NOT modify shared objects (keys and values) in-place. 
```

2022-06-14 09:07 UTC, rymsha commented on modules/lib/lib-grid/src/main/resources/lib/xp/grid.js
> + * @param {string|number} params.key - key the key whose associated value is to be returned
we support more than string or number

2022-06-15 13:39 UTC, rymsha approved these changes

2022-06-15 13:39 UTC, rymsha commented on modules/lib/lib-grid/src/main/resources/lib/xp/grid.js
> +}
```suggestion
};
```

2022-06-15 13:39 UTC, rymsha commented on modules/lib/lib-grid/src/main/resources/lib/xp/grid.js
> + * @param {string|number} key - key the key whose associated value is to be returned
```suggestion
 * @param {string} key - key the key whose associated value is to be returned
```

2022-06-15 13:39 UTC, rymsha commented on modules/lib/lib-grid/src/main/resources/lib/xp/grid.js
> + * @param {string|number} params.key key of the entry
```suggestion
 * @param {string} params.key key of the entry
```

2022-06-15 13:58 UTC, alansemenov commented on modules/lib/lib-grid/src/main/resources/lib/xp/grid.js
> +};
Codacy has a fix for the issue: [Unnecessary semicolon.](https://app.codacy.com/gh/enonic/xp/pullRequest?prid=9567561)
```suggestion
}
```

2022-06-15 15:31 UTC, merged