#7571 Correctly process links with query parameters
enonic/xp pull request #9521
Opened 2022-06-27 12:06 UTC by anatol-sialitski

2022-06-27 12:18 UTC, rymsha requested changes
this is not according to spec.

2022-06-27 14:25 UTC, rymsha requested changes

2022-06-27 14:25 UTC, rymsha commented on modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/url/HtmlLinkProcessor.java
> +            urlSuffix.append( "?" ).append( decodeParameterValue( queryParamsAsMap.get( "query" ) ) );
you should check that query does not contain illegal characters after `decodeParameterValue( queryParamsAsMap.get( "query" )`

2022-06-27 14:25 UTC, rymsha commented on modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/url/HtmlLinkProcessor.java
> +            urlSuffix.append( "#" ).append( decodeParameterValue( queryParamsAsMap.get( "fragment" ) ) );
you should check that query does not contain illegal characters after `decodeParameterValue( queryParamsAsMap.get( "fragment" )`

2022-06-27 14:25 UTC, rymsha commented on modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/url/HtmlLinkProcessor.java
> +
resulting pageUrl must be html (attribute) encoded

2022-06-28 12:00 UTC, vbradnitski approved these changes

2022-06-28 12:04 UTC, merged