Add config to disable html area sanitizing #9638
enonic/xp pull request #9654
Opened 2022-08-23 08:19 UTC by vbradnitski

2022-08-23 11:01 UTC, anatol-sialitski commented on modules/core/core-content/src/main/java/com/enonic/xp/core/impl/content/processor/HtmlAreaContentProcessor.java
> +@Component(configurationPid = "com.enonic.xp.admin")
use `configurationPid = "com.enonic.xp.content"` instead

2022-08-23 11:06 UTC, anatol-sialitski commented on modules/core/core-content/src/test/java/com/enonic/xp/core/impl/content/processor/HtmlAreaContentProcessorTest.java
> +        contentConfig = Mockito.mock( ContentConfig.class );
You can write that instead
```
ContentConfig contentConfig = mock( ContentConfig.class, invocation -> invocation.getMethod().getDefaultValue() );
```

2022-08-23 13:08 UTC, rymsha requested changes
also double check why sanitizer replaces nbsp with non-breaking

2022-08-23 14:19 UTC, rymsha requested changes

2022-08-23 14:19 UTC, rymsha commented on modules/runtime/src/home/config/com.enonic.xp.content.cfg
> +#htmlarea.sanitizing.enabled = true
change dafault to `false` and don't mention it in config file

2022-08-25 11:24 UTC, rymsha requested changes

2022-08-25 11:24 UTC, rymsha commented on modules/runtime/src/home/config/com.enonic.xp.content.cfg
> +#htmlarea.sanitizing.enabled = false
delete this line

2022-08-25 14:06 UTC, rymsha requested changes

2022-08-25 14:06 UTC, rymsha commented on modules/core/core-internal/src/main/java/com/enonic/xp/core/internal/processor/InternalHtmlSanitizer.java
> +    public static String sanitize( final String value, final boolean strict )
Use two factory methods instead

2022-08-26 07:24 UTC, rymsha approved these changes

2022-08-26 07:30 UTC, anatol-sialitski approved these changes

2022-08-26 08:17 UTC, merged