add config to disable and set priority for virtual apps #9624
enonic/xp pull request #9662
Opened 2022-08-29 14:29 UTC by vbradnitski

2022-08-30 07:23 UTC, anatol-sialitski approved these changes

2022-09-01 18:25 UTC, rymsha requested changes
We changed spec

2022-09-05 13:03 UTC, rymsha requested changes

2022-09-05 13:03 UTC, rymsha commented on modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/ApplicationFactory.java
> +                return new RealOverVirtualApplicationUrlResolver( bundleUrlResolver, classLoaderUrlResolver, nodeResourceApplicationResolver );
use `MultiApplicationUrlResolver` for bundleUrlResolver and  classLoaderUrlResolver

2022-09-05 13:36 UTC, rymsha approved these changes

2022-09-06 06:40 UTC, rymsha approved these changes

2022-09-06 07:14 UTC, merged