Developer role #9661
enonic/xp pull request #9671
Opened 2022-09-02 12:20 UTC by vbradnitski

2022-09-05 13:05 UTC, rymsha requested changes
Need to move role init into initializer of app repository

2022-09-08 07:23 UTC, rymsha requested changes
Rename Developer everywhere 

Also where is a test to check that without Schema Admin role no apps or schemas can be managed?

2022-09-09 14:41 UTC, rymsha approved these changes

2022-09-12 09:21 UTC, anatol-sialitski approved these changes

2022-09-12 10:26 UTC, merged