Improve processHtml #9413
enonic/xp pull request #9673
Opened 2022-09-05 12:26 UTC by anatol-sialitski

2022-09-06 10:57 UTC, vbradnitski approved these changes

2022-09-08 07:40 UTC, rymsha requested changes

2022-09-08 07:40 UTC, rymsha commented on modules/portal/portal-api/src/main/java/com/enonic/xp/portal/url/HtmlProcessorParams.java
> +public class HtmlProcessorParams
```suggestion
public final class HtmlProcessorParams
```

2022-09-08 07:40 UTC, rymsha commented on modules/portal/portal-api/src/main/java/com/enonic/xp/portal/url/HtmlProcessorParams.java
> +    public static class Builder
```suggestion
    public static final class Builder
```

2022-09-08 07:40 UTC, rymsha commented on modules/portal/portal-api/src/main/java/com/enonic/xp/portal/url/HtmlProcessorParams.java
> +
Add private constuctor

2022-09-08 07:40 UTC, rymsha commented on modules/portal/portal-api/src/main/java/com/enonic/xp/portal/url/ProcessHtmlParams.java
> +    private boolean useCustomMacrosProcessing = false;
It should be called `processMacros` with default `true`

2022-09-09 10:24 UTC, rymsha approved these changes

2022-09-09 10:24 UTC, merged