Add logout button on the 403 page #9151
enonic/xp pull request #9713
Opened 2022-09-19 12:57 UTC by anatol-sialitski

2022-09-20 14:41 UTC, rymsha approved these changes

2022-09-20 14:43 UTC, rymsha requested changes
It looks like any error page gets logout button, not just 403 one.

2022-09-21 09:49 UTC, alansemenov approved these changes

2022-09-23 09:23 UTC, rymsha requested changes

2022-09-23 09:23 UTC, rymsha commented on modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/exception/ErrorPageSimpleBuilder.java
> +        if ( this.statusCode == HttpStatus.FORBIDDEN.value() )
It should check existence of logout url, not the status

2022-09-25 20:16 UTC, rymsha requested changes

2022-09-25 20:16 UTC, rymsha commented on modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/exception/ExceptionInfo.java
> +        return this.portalUrlService.identityUrl( params );
There should be no logout url if not authenticated

2022-09-26 09:37 UTC, rymsha approved these changes

2022-09-26 10:11 UTC, vbradnitski approved these changes

2022-09-26 10:43 UTC, merged