Specify resource resolver via context #9623
enonic/xp pull request #9715
Opened 2022-09-19 17:57 UTC by vbradnitski

2022-09-20 14:32 UTC, rymsha requested changes

2022-09-20 14:32 UTC, rymsha commented on modules/core/core-app/src/main/java/com/enonic/xp/core/impl/app/ApplicationFactory.java
> +        switch ( name )
we are missing one which is `new MultiApplicationUrlResolver( classLoaderUrlResolver, bundleUrlResolver )`. Let's call it "real" for now

2022-09-28 13:07 UTC, rymsha approved these changes

2022-09-29 12:17 UTC, anatol-sialitski approved these changes

2022-10-04 16:07 UTC, rymsha approved these changes

2022-10-05 08:21 UTC, merged