application getApplicationMode method instead of hasVirtua/hasReal #9757
enonic/xp pull request #9764
Opened 2022-10-04 13:50 UTC by vbradnitski

2022-10-04 15:07 UTC, rymsha requested changes

2022-10-04 15:07 UTC, rymsha commented on modules/lib/lib-app/src/main/resources/lib/xp/examples/app/getApplicationMode.js
>  // Create virtual app.
```suggestion
// Get Application mode.
```

2022-10-05 16:33 UTC, rymsha approved these changes

2022-10-06 07:49 UTC, anatol-sialitski commented on modules/lib/lib-app/src/main/resources/lib/xp/app.ts
> +    execute(): string;
`string | null` instead `string`

2022-10-06 08:35 UTC, merged