Make Node in node library generic #9794
enonic/xp pull request #9798
Opened 2022-10-13 20:10 UTC by edloidas

2022-10-14 09:00 UTC, tajakobsen requested changes
Isn't relying on the `ScriptValue` type from global still a problem?

2022-10-14 09:04 UTC, edloidas commented on modules/lib/lib-node/src/main/resources/lib/xp/node.ts
> +    create<NodeData>(node: ScriptValue): Node<NodeData>;
No. `NodeHandler` is the internal class, that is linked to the Java NodeHandler. It's not imported and won't be present in DTS or JS files.

2022-10-14 09:54 UTC, alansemenov approved these changes

2022-10-17 10:00 UTC, tajakobsen approved these changes
Looks good

2022-10-17 10:19 UTC, merged