Disallow anonymous access to draft branch #9853
enonic/xp pull request #9944
Opened 2022-12-30 14:28 UTC by anatol-sialitski

2023-01-03 06:51 UTC, rymsha requested changes

2023-01-03 06:51 UTC, rymsha commented on modules/launcher/launcher-impl/src/main/resources/META-INF/config/system.properties
> +# xp.disallow.access.to.draft.branch.for.anonymous = true
It should be a portal config. Not a global config.
Config should specify principals who have access

2023-01-03 06:51 UTC, rymsha commented on modules/portal/portal-api/src/main/java/com/enonic/xp/portal/handler/BasePortalHandler.java
> +            doHandleBeforeNextInChain( portalRequest );
Avoid new API method. It should be possible to do without extending API

2023-01-03 06:51 UTC, rymsha commented on modules/portal/portal-impl/src/main/java/com/enonic/xp/portal/impl/handler/portal/SiteHandler.java
> +            if ( !( authInfo.hasRole( RoleKeys.ADMIN ) || authInfo.hasRole( RoleKeys.ADMIN_LOGIN ) ) &&
Anonymous should get Authentication Required 
Any other with insufficient rights should get Forbidden

2023-01-03 15:48 UTC, vbradnitski approved these changes

2023-01-04 10:08 UTC, rymsha approved these changes

2023-01-04 10:08 UTC, rymsha commented on modules/runtime/src/home/config/com.enonic.xp.portal.cfg
> +#draftBranchAllowedFor = role:system.admin, role:system.admin.login
delete `role:system.admin` from this list.

2023-01-04 17:55 UTC, merged