Allow to customize base URL for URL rewriting in portal.url functions #9686
enonic/xp pull request #9946
Opened 2023-01-02 13:12 UTC by anatol-sialitski

2023-01-03 06:37 UTC, rymsha requested changes

2023-01-03 06:37 UTC, rymsha commented on modules/web/web-api/src/main/java/com/enonic/xp/web/servlet/ServletRequestUrlHelper.java
> +        str.append( "://" ).append( Objects.requireNonNullElse( getCustomHostFromContext(), req.getServerName() ) );
Configuring host is not sufficient. It should be baseUrl.
Example: `https://example.com/some/path`

2023-01-03 06:37 UTC, rymsha commented on modules/web/web-api/src/main/java/com/enonic/xp/web/servlet/ServletRequestUrlHelper.java
> +    private static String getCustomHostFromContext()
This attribute does not need to have a helper method. Remove

2023-01-09 20:07 UTC, vbradnitski approved these changes

2023-01-10 06:56 UTC, rymsha requested changes
It doesn't solve the problem. Back to whiteboard.

2023-11-09 20:40 UTC, closed without merging