Store app config on /content node #9947
enonic/xp pull request #9953
Opened 2023-01-09 20:09 UTC by vbradnitski

2023-01-10 07:18 UTC, rymsha requested changes

2023-01-10 07:18 UTC, rymsha commented on modules/core/core-api/src/main/java/com/enonic/xp/project/Project.java
> +    public static Project from( final Repository repository, final PropertyTree nodeData )
SiteConfigs instead of nodeData

2023-01-10 07:18 UTC, rymsha commented on modules/core/core-project/src/main/java/com/enonic/xp/core/impl/project/ProjectServiceImpl.java
> +        return Project.from( repositoryService.get( params.getName().getRepoId() ), getContentRootData( params.getName() ) );
It is problematic to fetch data right after saving. Maybe there is a way to avoid fetch?

2023-01-10 07:18 UTC, rymsha commented on modules/core/core-project/src/main/java/com/enonic/xp/core/impl/project/ProjectServiceImpl.java
> +        return doGet( params.getName() );
Same as above

2023-01-10 07:18 UTC, rymsha commented on modules/core/core-project/src/main/java/com/enonic/xp/core/impl/project/ProjectServiceImpl.java
> +        if ( !this.repositoryService.isInitialized( projectName.getRepoId() ) )
Strange to see isInitialazed here. It is supposed to be called from initializer only

2023-01-10 07:18 UTC, rymsha commented on modules/core/core-project/src/main/java/com/enonic/xp/core/impl/project/ProjectServiceImpl.java
> +            .repositoryId( projectName.getRepoId() )
Same code repeated

2023-01-12 14:52 UTC, anatol-sialitski approved these changes

2023-01-12 19:11 UTC, rymsha requested changes

2023-01-12 19:11 UTC, rymsha commented on modules/core/core-project/src/main/java/com/enonic/xp/core/impl/project/ProjectServiceImpl.java
> +            LOG.debug( "Project created: " + params.getName() );
Use {} syntax

2023-01-12 19:11 UTC, rymsha commented on modules/core/core-repo/src/main/java/com/enonic/xp/repo/impl/node/NodeServiceImpl.java
> +            InternalContext.create( ContextAccessor.current() ).searchPreference( SearchPreference.LOCAL ).build();
Why? Commit must be on primary

2023-01-14 11:12 UTC, rymsha approved these changes

2023-01-17 07:53 UTC, merged