Move variantOf field assignment from Node API to Content API #9957
enonic/xp pull request #9963
Opened 2023-01-19 12:50 UTC by anatol-sialitski

2023-01-19 16:05 UTC, rymsha approved these changes

2023-01-19 16:05 UTC, rymsha commented on modules/core/core-api/src/main/java/com/enonic/xp/content/DuplicateContentParams.java
> +        private boolean variant = false;
```suggestion
        private boolean variant;
```

2023-01-19 16:05 UTC, rymsha commented on modules/core/core-api/src/main/java/com/enonic/xp/content/DuplicateContentParams.java
> +            if ( this.variant && this.includeChildren )
Preconditions.checkArgument

2023-01-20 09:15 UTC, vbradnitski requested changes

2023-01-20 09:15 UTC, vbradnitski commented on modules/core/core-api/src/main/java/com/enonic/xp/content/DuplicateContentParams.java
> +        public Builder variant( final Boolean variant )
can't we use simple 'boolean' here?

2023-01-20 09:15 UTC, rymsha requested changes

2023-01-20 09:15 UTC, rymsha commented on modules/core/core-api/src/main/java/com/enonic/xp/content/DuplicateContentParams.java
> +        public Builder variant( final Boolean variant )
```suggestion
        public Builder variant( final boolean variant )
```

2023-01-20 09:22 UTC, vbradnitski approved these changes

2023-01-20 09:25 UTC, rymsha approved these changes

2023-01-20 11:00 UTC, merged