TypeScript Make objects with object properties generic #9556
enonic/xp pull request #9972
Opened 2023-01-19 17:39 UTC by edloidas

2023-01-20 11:38 UTC, tajakobsen requested changes
Good job. Think a bit about where it's smart to have *default type parameters*. I think it's maybe only on functions if the users are not creating instances of this object themselves.

2023-01-20 11:38 UTC, tajakobsen commented on modules/lib/lib-auditlog/src/main/resources/lib/xp/auditlog.ts
> +export interface AuditLogParams<DATA extends Record<string, unknown> = Record<string, unknown>> {
The convention used other places in the code is that type parameters are capitalized (not upper case).

```suggestion
export interface AuditLogParams<Data extends Record<string, unknown> = Record<string, unknown>> {
```

2023-01-20 11:38 UTC, tajakobsen commented on modules/lib/lib-auditlog/src/main/resources/lib/xp/auditlog.ts
> +export interface AuditLogParams<DATA extends Record<string, unknown> = Record<string, unknown>> {
Where is it smart to have default type parameters (` = Record<string, unknown>`)? I'm thinking maybe on the functions, and not in the interfaces. Specially when the objects are only created by this library.

(This goes for the other cases below too.)

What do you think?

2023-01-20 11:38 UTC, tajakobsen commented on modules/lib/lib-project/src/main/resources/lib/xp/project.ts
> +export interface CreateProjectParams<CONFIG extends Record<string, unknown> = Record<string, unknown>> {
The same comments as above. Don't uppercase type parameters, and think through where we want default type parameters (I think we maybe only want them on functions).

2023-01-20 11:39 UTC, ComLock approved these changes
One problem with the current positional generics, is keeping backwards compatibility when one wants to add more generics later on.

Hopefully named generics will be added soon (give it a thumbs up?):
https://github.com/microsoft/TypeScript/issues/38913

2023-01-23 09:35 UTC, edloidas commented
@tajakobsen Agree on all points. Had an uppercased template names in other project I worked on before this commit, so unintentionally used this style here too.
As for the default type params, we have an inconsistency across the project, so I looked through all the files and updated them: Params won't have defaults, but functions will. The result types, like AuditLog, Content, etc will also have a default type params in most of the cases.

2023-01-23 12:51 UTC, tajakobsen approved these changes
Looks good.

2023-01-23 13:07 UTC, merged