Extend Node JS API with duplicate node function #9968
enonic/xp pull request #9999
Opened 2023-01-25 15:38 UTC by anatol-sialitski

2023-01-25 15:40 UTC, vbradnitski approved these changes

2023-01-25 16:43 UTC, rymsha requested changes

2023-01-25 16:43 UTC, rymsha commented on modules/lib/lib-node/src/main/resources/lib/xp/node.ts
> +     * @param {object} [params.includeChildren=true] Indicates that children nodes must be duplicated, too.
boolean

2023-01-25 16:43 UTC, rymsha commented on modules/lib/lib-node/src/main/resources/lib/xp/node.ts
> +     * @param {object} [params.refresh] Refresh the index for the current repoConnection.
string

2023-01-25 16:43 UTC, rymsha commented on modules/lib/lib-node/src/main/resources/lib/xp/node.ts
> +     * @param {object} [params.dataProcessor] Node data processor.
function

2023-01-26 08:05 UTC, rymsha approved these changes

2023-01-26 08:28 UTC, edloidas approved these changes

2023-01-26 08:57 UTC, merged